//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoProduccion
    {
        public int IdCosto { get; set; }
        public int IdProducto { get; set; }
        public int IdMatriaPrima { get; set; }
        public int TotalMateriaPrima { get; set; }
        public decimal PagoHoras { get; set; }
        public int HorasTrabajadas { get; set; }
        public decimal TotalPagoManoObra { get; set; }
    
        public virtual EntradaMateriaPrima EntradaMateriaPrima { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
