//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaMateriaPrima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntradaMateriaPrima()
        {
            this.CostoProduccion = new HashSet<CostoProduccion>();
        }
    
        public int IdMatriaPrima { get; set; }
        public int IdProveedor { get; set; }
        public int IdInventario { get; set; }
        public string NombreMateriaPrima { get; set; }
        public System.DateTime FechaEntrante { get; set; }
        public int CantidadEntrante { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioxUnidad { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostoProduccion> CostoProduccion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
