// <auto-generated />
namespace PymesS.A.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creando_SPS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creando_SPS));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161908433_Creando_SPS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
